# Generated by Django 4.2.6 on 2023-10-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(upload_to='static/blog_images')),
                ('blog_title', models.CharField(max_length=20000)),
                ('blog_description', models.CharField(max_length=10000)),
            ],
            options={
                'verbose_name': 'Blog Detail',
            },
        ),
        migrations.CreateModel(
            name='OurVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_image', models.ImageField(upload_to='static/vision_image')),
                ('vision_label', models.CharField(max_length=1000)),
                ('vision_description_line_1', models.CharField(max_length=10000)),
                ('vision_description_line_2', models.CharField(max_length=10000)),
                ('vision_description_line_3', models.CharField(blank=True, max_length=10000, null=True)),
                ('vision_description_line_4', models.CharField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'verbose_name': 'Vision Content',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_image', models.ImageField(blank=True, null=True, upload_to='static/vision_image')),
                ('customer_name', models.CharField(max_length=10000)),
                ('customer_review', models.CharField(max_length=10000)),
            ],
            options={
                'verbose_name': 'Customer Review',
            },
        ),
    ]
