# Generated by Django 4.2.6 on 2023-10-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_images', models.ImageField(upload_to='static/banner_images')),
            ],
            options={
                'verbose_name': 'Banner Image',
            },
        ),
    ]
