# Generated by Django 4.2.6 on 2023-10-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_bannerimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimages',
            name='banner_images',
            field=models.ImageField(upload_to='courses/static/banner_images'),
        ),
    ]
