# Generated by Django 4.2.6 on 2023-10-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_bannerimages_banner_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimages',
            name='banner_images',
            field=models.ImageField(upload_to='static/banner_images'),
        ),
    ]
