# Generated by Django 4.2.6 on 2023-10-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_name', models.CharField(max_length=10000)),
                ('founder_image', models.ImageField(upload_to='static/founder_images')),
            ],
            options={
                'verbose_name': 'Founder Detail',
            },
        ),
    ]
