# Generated by Django 4.2.6 on 2023-10-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=10000)),
                ('branch_address', models.CharField(max_length=10000)),
                ('branch_contact_number_1', models.CharField(max_length=10000)),
                ('branch_contact_number_2', models.CharField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'verbose_name': 'Branch Detail',
            },
        ),
    ]
