# Generated by Django 4.2.6 on 2023-10-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_image',
            field=models.ImageField(default=1, upload_to='static/branch_images'),
            preserve_default=False,
        ),
    ]
