# Generated by Django 4.2.6 on 2023-10-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=10000)),
                ('course_image', models.ImageField(upload_to='static/images')),
                ('course_description', models.TextField(max_length=10000)),
            ],
            options={
                'verbose_name': 'Course Detail',
            },
        ),
    ]
