# Generated by Django 4.2.6 on 2023-10-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_courses_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_description_line_1',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_description_line_2',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_description_line_3',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_description_line_4',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
