# Generated by Django 4.2.6 on 2023-10-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(max_length=20000)),
                ('contact_number', models.CharField(max_length=10000)),
                ('email_address', models.CharField(max_length=10000)),
                ('address', models.CharField(max_length=10000)),
                ('time', models.CharField(max_length=10000)),
            ],
            options={
                'verbose_name': 'Contact Detail',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=10000, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=10000, null=True)),
                ('twitter', models.CharField(blank=True, max_length=10000, null=True)),
                ('instagram', models.CharField(blank=True, max_length=10000, null=True)),
                ('youtube', models.CharField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'verbose_name': 'Social Links',
            },
        ),
    ]
