# Generated by Django 4.2.6 on 2023-10-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedialinks',
            options={'verbose_name': 'Social Link'},
        ),
    ]
