# Generated by Django 4.2.6 on 2023-10-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1000)),
                ('description_line_1', models.CharField(blank=True, max_length=10000, null=True)),
                ('description_line_2', models.CharField(blank=True, max_length=10000, null=True)),
                ('description_line_3', models.CharField(max_length=10000)),
                ('description_line_4', models.CharField(max_length=10000)),
            ],
            options={
                'verbose_name': 'Institute Facilities',
            },
        ),
    ]
